version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
  logstash:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/logstash/logstash:7.6.0
    volumes:
      - ./logstash/data:/usr/share/data
      - ./logstash/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/settings/logstash-dev.conf:/usr/share/logstash/config/logstash-dev.conf
      - ./logstash/logs:/usr/share/logstash/logs
    environment: 
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    command: ["logstash","-f", "config/logstash-dev.conf"]
    restart: always
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - ${PORT_KIBANA}
    restart: always
  filebeat:
    build: .
    depends_on:
      - logstash
    user: "root"
    volumes:
      - ./filebeat-docker/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - C:/Users/Jose_Lopez/MERCATINL-DEV/wildfly-17.0.1.Final/standalone/log:/usr/share/filebeat/log-generatorg
    command: ["filebeat","-e","-c", "/usr/share/filebeat/filebeat.yml","-strict.perms=false"]
    restart: always